services:
  api:
    command: >
      sh -c "npm run migration:run && npm run start:dev"
    depends_on:
      - my_database
    ports:
      - "${APP_PORT}:${APP_PORT}"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=${APP_PORT}
      #- DATABASE_URL=${DATABASE_URL}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRE_IN=${JWT_ACCESS_TOKEN_EXPIRE_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_TOKEN_EXPIRE_IN=${JWT_REFRESH_TOKEN_EXPIRE_IN}
      - THROTTLER_LIMIT=${THROTTLER_LIMIT}
      - THROTTLER_TTL=${THROTTLER_TTL}
      - BASE_URL=${BASE_URL}
    restart: unless-stopped
  my_database:
    image: 'mariadb:10.5'
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - database_data:/var/lib/mysql
volumes:
  database_data:
